### PR TITLE
Fix error overwriting search results in AddContact

### LINKED ISSUE #1056: Errors in Contact search will remove successful search results
IMG_3205

in this case, I had found matches to my search but then the error appeared and they went away.

### PR DESCRIPTION
**Pull request by undercase**
Fixes #1056. Two main changes:

1. In the contacts search reducer, leaves results in the state when processing error action.
2. In the selector, will display the error (if there is one) and the results already loaded.

### CODE REVIEW

**Comment by asutula** [comment]
Don't want this one to get too far out of date... what's the hold up @undercase ?

**Comment by undercase** [comment]
@asutula No hold up, this one totally slipped my mind. Merging it right now.

**Comment by undercase** [comment]
The ios test just timed out, so I can't merge this now.

**Comment by andrewxhill** [comment]
ftfy!

**Comment by undercase** [comment]
Thanks!

**Pull request merged**
