### PR TITLE
SDK 2.1

### PR DESCRIPTION
**Pull request by sanderpick**
Opening this on your branch @asutula in order to discuss the changes.

### CODE REVIEW

**Comment by sanderpick** [comment]
I missed a couple @ReactMethod annotations in the bridge... fix coming.

**Comment by sanderpick** [comment]
Updated.

**Comment by sanderpick** [comment]
After https://github.com/textileio/react-native-sdk/pull/122 is merged, we can bump the SDK to `2.1.0`.

**Comment by asutula** [comment]
Ok i've pulled in the official rn sdk release and made minimal updates to the app code to get it working. There are still some rough edges, the biggest one being there is no visual feedback about file sync state. There's also still lots of redux code that can be cleaned up now that we handle all image adding/sharing the same.

We can/should get this in beta asap and I can continue work on those issues tomorrow. No turning back anyways. Objections?

cc @sanderpick

**Comment by asutula** [comment]
Oh other big outstanding issue for tomorrow: Fall back to `Files.target` when `Files.data` isn't available.

**Comment by asutula** [comment]
@sanderpick mind looking at that android CI fail?

**Comment by sanderpick** [comment]
Oop, sorry for the delay... I need to turn my desktop email notifications back on since I've muted our bot channels. Looking...

**Comment by sanderpick** [comment]
Ok, @asutula - looking green again.

**Pull request merged**
