### PR TITLE
detects the error i see "unauthorized" and triggers a cafe session refresh

### PR DESCRIPTION
**Pull request by andrewxhill**
Signed-off-by: andrew <andrew@textile.io>

### CODE REVIEW

**Comment by undercase** [comment]
I also need this-started getting the unauthorized error on my iPhone.

**Comment by asutula** [comment]
Andrews phone was in a state where his refresh token was expired, so he was basically stuck because the app doesn’t currently deal with re registering the cafe in that case. 

Maybe you’re in the same situation, but I doubt it. You can check it the status of your sessions by going to the settings menu in verbose mode and tapping on Cafes. You can refresh your session there if necessary. 

I’m considering making an issue to have the app deal with cafe re registration in the case of expired refresh tokens, but all of this stuff is being moved to the native sdks in the next update.

**Comment by undercase** [comment]
Just did this, and that was the issue. They were both expired.

**Comment by sanderpick** [comment]
@asutula sounds good... we can tag on a `ReRegisterCafe` method that should help here too. No need to re-announce to contacts.

**Comment by asutula** [comment]
Were you able to refresh the token @thomas or are you stuck as well?

**Comment by undercase** [comment]
I’m stuck.

**Comment by andrewxhill** [comment]
what's going on here?

**Comment by asutula** [comment]
There’s a more general fix for refreshing expired session in the photos app and in the sdk layer. The photos app fix is the quicker short term fix and I’ll have a pr out today. Longer term sdk fix is wip and not top priority

**Comment by asutula** [comment]
Fixed in https://github.com/textileio/photos/pull/1214

**Pull request closed without merging**
