### PR TITLE
Updates register cafe step

### PR DESCRIPTION
**Pull request by andrewxhill**
because cafe.url was not part of the existing Config model, I've added a method to just get it from the gateway, now just using the local config to pull in the token when needed. Will add a few comments here too.

### CODE REVIEW

**Comment by sanderpick** [comment]
I figured URL must be available since it’s displayed on the cafes screen. What does gateway mean here? The remote gateway?

**Comment by andrewxhill** [comment]
It's known _after_ registration via peerId. Looks like config has name, peerId, token. So, I'm just grabbing from here, `https://gateway.textile.cafe/cafes`, for production. For beta/dev it's known, but i still do a check to make sure it's working the same.

**Comment by andrewxhill** [comment]
For dev && beta, even though already known, I just do two checks to `https://us-west-dev.textile.cafe` and `https://us-west-beta.textile.cafe`

**Comment by sanderpick** [comment]
Can you should just change the config to include url and remove peerID? I can tell you what the URLs are. They’re also in 1Password. That gateway endpoint doesn’t contain the new production cafes.

**Comment by andrewxhill** [comment]
Ah, yeah, we can do that then. Will reconfig.

**Comment by andrewxhill** [comment]
k, that should be gtg now

**Pull request merged**
