### PR TITLE
Contact multi select -> new group

### PR DESCRIPTION
**Pull request by undercase**
This was a really cool one to work on. Basic flow:

1. Press "New Group" in upper right hand corner of the contacts screen.
2. Select some contacts.
3. Press "Create a new group with [#] contacts" button at the bottom of the screen.
4. This opens a modal to name the new group.

### CODE REVIEW

**Comment by sanderpick** [comment]
Dude, yes! 🏆🏆🏆

**Comment by asutula** [comment]
Gonna merge master in here so i can run it locally

**Comment by asutula** [comment]
Awesome work. Can't wait to get this in!

**Comment by undercase** [comment]
@asutula Fixed these issues.

**Pull request merged**
